// import type { Metadata } from "next"
// import { Inter } from 'next/font/google'
// import "./globals.css"
// import Header from "../app/components/header";
// import Footer from "../app/components/footer";
// import MainNav from "../app/components/main-nav";


// const inter = Inter({ subsets: ["latin"] })

// export const metadata: Metadata = {
//   title: "Comforty - Furniture Store",
//   description: "Best Furniture Collection For Your Interior",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <div className="max-w-[1920px] mx-auto">
//           <header>
//             <Header />
//             <MainNav />
//           </header>
//           <main>{children}</main>
//         </div>
//         <Footer />
//       </body>
//     </html>
//   )
// }

// import { CartProvider } from './contexts/CartContext'
// import './globals.css'
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

// export const metadata = {
//   title: 'Next.js E-commerce with Sanity',
//   description: 'An e-commerce site built with Next.js and Sanity',
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <CartProvider>
//         <body className={inter.className}>{children}</body>
//       </CartProvider>
//     </html>
//   )
// }

// import "./globals.css"
// import { Inter } from "next/font/google"
// import Navbar from "./components/main-nav"
// import Footer from "./components/footer"

// const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
        
//           <Navbar />
//           {children}
//           <Footer />
//       </body>
//     </html>
//   )
// }

// import "./globals.css"
// import { Inter } from "next/font/google"
// import Navbar from "./components/main-nav"
// import { CartProvider } from "./contexts/CartContext"
// import Footer from "./components/footer"

// const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CartProvider>
//           <Navbar />
//           {children}
//         </CartProvider>
//       </Footer>
//       </body>
//     </html>
//   )
// }
// last one 
// import "./globals.css"
// import { Inter } from "next/font/google"
// // import Navbar from "../../../../../components/Navbar"
// import MainNav from "../app/components/main-nav";
// import { CartProvider } from "./context/CartContext"
// import { Toaster } from "sonner"

// const inter = Inter({ subsets: ["latin"] })

// export const metadata = {
//   title: "Dine Market",
//   description: "Discover fashion that suits your style",
// }

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode
// }) {
//   return (
//     <html lang="en">
//       <body className={inter.className}>
//         <CartProvider>
//           <MainNav />
//           {children}
//           <Toaster position="top-center" />
//         </CartProvider>
//       </body>
//     </html>
//   )
// }

import "./globals.css"
import { Inter } from "next/font/google"
import MainNav from "../app/components/main-nav";
import { CartProvider } from "./context/CartContext"
import { Toaster } from "sonner"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Dine Market",
  description: "Discover fashion that suits your style",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider>
          <MainNav />
          {children}
          <Toaster position="top-center" richColors />
        </CartProvider>
      </body>
    </html>
  )
}

